export const labels = [
  {
    name: "good first issue",
    color: "#7057ff",
    description: "Good for newcomers",
    icon: "random",
  },
  {
    name: "help wanted",
    color: "#008672",
    description: "Extra attention is needed",
    icon: "random",
  },
  {
    name: "priority: critical",
    color: "#b60205",
    description: "",
    icon: "random",
  },
  {
    name: "priority: high",
    color: "#d93f0b",
    description: "",
    icon: "random",
  },
  {
    name: "priority: low",
    color: "#0e8a16",
    description: "",
    icon: "random",
  },
  {
    name: "priority: medium",
    color: "#fbca04",
    description: "",
    icon: "random",
  },
  {
    name: "status: can't reproduce",
    color: "#fec1c1",
    description: "",
    icon: "random",
  },
  {
    name: "status: confirmed",
    color: "#215cea",
    description: "",
    icon: "random",
  },
  {
    name: "status: duplicate",
    color: "#cfd3d7",
    description: "This issue or pull request already exists",
    icon: "random",
  },
  {
    name: "status: needs information",
    color: "#fef2c0",
    description: "",
    icon: "random",
  },
  {
    name: "status: wont do/fix",
    color: "#eeeeee",
    description: "This will not be worked on",
    icon: "random",
  },
  {
    name: "type: bug",
    color: "#d73a4a",
    description: "Something isn't working",
    icon: "random",
  },
  {
    name: "type: discussion",
    color: "#d4c5f9",
    description: "",
    icon: "random",
  },
  {
    name: "type: documentation",
    color: "#006b75",
    description: "",
    icon: "random",
  },
  {
    name: "type: enhancement",
    color: "#84b6eb",
    description: "",
    icon: "random",
  },
  {
    name: "type: epic",
    color: "#3e4b9e",
    description: "A theme of work that contain sub-tasks",
    icon: "random",
  },
  {
    name: "type: feature request",
    color: "#fbca04",
    description: "New feature or request",
    icon: "random",
  },
  {
    name: "type: question",
    color: "#d876e3",
    description: "Further information is requested",
    icon: "random",
  },
];
